hydra:
  output_subdir: null

save_model_path: model_weights/model_weights.pt

dataset:
  root: ../data # for GCP - use "data/""
  dataset: FashionMNIST # for VAE purposes or Flowers102

train:
  epochs: 2
  lr: 0.001
  weight_decay: 5e-4

show_model_summary: True
num_classes : 20